/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclerentalservice;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rr1
 */
public class AdminAddCar extends javax.swing.JFrame {

    /**
     * Creates new form AdminAddCar
     */
    public AdminAddCar() {
        initComponents();
        con=null;
        pst=null;
        rs=null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_vehiclerentalservice = new javax.swing.JLabel();
        lbl_addcar = new javax.swing.JLabel();
        lbl_modelnumber = new javax.swing.JLabel();
        lbl_enginenumber = new javax.swing.JLabel();
        lbl_buydate = new javax.swing.JLabel();
        lbl_carcondition = new javax.swing.JLabel();
        cb_carcondition = new javax.swing.JComboBox<>();
        txt_modelnumber = new javax.swing.JTextField();
        txt_enginenumber = new javax.swing.JTextField();
        txt_buydate = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();
        btn_addmodel = new javax.swing.JButton();
        btn_addmodel1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(123, 104, 238));

        lbl_vehiclerentalservice.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_vehiclerentalservice.setForeground(new java.awt.Color(255, 255, 255));
        lbl_vehiclerentalservice.setText("VEHICLE RENTAL SERVICE");

        lbl_addcar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_addcar.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addcar.setText("ADD CAR");

        lbl_modelnumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_modelnumber.setForeground(new java.awt.Color(255, 255, 255));
        lbl_modelnumber.setText("Model Number");

        lbl_enginenumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_enginenumber.setForeground(new java.awt.Color(255, 255, 255));
        lbl_enginenumber.setText("Engine Number");

        lbl_buydate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_buydate.setForeground(new java.awt.Color(255, 255, 255));
        lbl_buydate.setText("Buy Date [yyyy-mm-dd]");

        lbl_carcondition.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_carcondition.setForeground(new java.awt.Color(255, 255, 255));
        lbl_carcondition.setText("Car Condition");

        cb_carcondition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excellent", "Good", "Average", "Bad", "Poor" }));

        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        btn_addmodel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_addmodel.setText("ADD MODEL");
        btn_addmodel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addmodelActionPerformed(evt);
            }
        });

        btn_addmodel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_addmodel1.setText("SEE ALL MODELS");
        btn_addmodel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addmodel1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_vehiclerentalservice)
                        .addGap(206, 206, 206))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_addcar)
                        .addGap(370, 370, 370))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_carcondition)
                                    .addComponent(lbl_modelnumber)
                                    .addComponent(lbl_enginenumber)
                                    .addComponent(lbl_buydate))
                                .addGap(156, 156, 156)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_buydate)
                                    .addComponent(txt_modelnumber)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cb_carcondition, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 116, Short.MAX_VALUE))
                                    .addComponent(txt_enginenumber)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_addmodel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(116, 116, 116)))
                        .addGap(206, 206, 206))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_addmodel, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lbl_vehiclerentalservice)
                .addGap(18, 18, 18)
                .addComponent(lbl_addcar)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(lbl_modelnumber))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(txt_modelnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_enginenumber)
                    .addComponent(txt_enginenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_buydate)
                    .addComponent(txt_buydate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_carcondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_carcondition))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addmodel)
                    .addComponent(btn_add)
                    .addComponent(btn_addmodel1))
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        try {
            // TODO add your handling code here:
            con = new Connector().getCon();
            pst = con.prepareStatement("SELECT * FROM `vehicle_rental`.`vehicle_model` WHERE id=?;");
            pst.setString(1, txt_modelnumber.getText());
            rs = pst.executeQuery();
            if(rs.next()) {
                pst = con.prepareStatement("INSERT INTO `vehicle_rental`.`rental_car` (`model`, `engine_no`, `buy_date`, `car_condition`) VALUES (?, ?, ?, ?);");
                pst.setString(1,txt_modelnumber.getText());
                pst.setString(2,txt_enginenumber.getText());
                pst.setString(3, txt_buydate.getText());
                pst.setString(4, cb_carcondition.getSelectedItem().toString());
                if(pst.executeUpdate()!=1) {
                    JOptionPane.showMessageDialog(null,"Error Occured. Contact Admin.");
                }
            }
            else {
                JOptionPane.showMessageDialog(null,"Given Model doesnot exist. Create model.");
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Linking Error. Contact admin.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
        }
    }//GEN-LAST:event_btn_addActionPerformed

    private void btn_addmodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addmodelActionPerformed
        // TODO add your handling code here:
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddModel().setVisible(true);
            }
        });
    }//GEN-LAST:event_btn_addmodelActionPerformed

    private void btn_addmodel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addmodel1ActionPerformed
        // TODO add your handling code here:
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSeeAllModels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSeeAllModels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSeeAllModels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSeeAllModels.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSeeAllModels().setVisible(true);
            }
        });
    }//GEN-LAST:event_btn_addmodel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JButton btn_addmodel;
    private javax.swing.JButton btn_addmodel1;
    private javax.swing.JComboBox<String> cb_carcondition;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_addcar;
    private javax.swing.JLabel lbl_buydate;
    private javax.swing.JLabel lbl_carcondition;
    private javax.swing.JLabel lbl_enginenumber;
    private javax.swing.JLabel lbl_modelnumber;
    private javax.swing.JLabel lbl_vehiclerentalservice;
    private javax.swing.JTextField txt_buydate;
    private javax.swing.JTextField txt_enginenumber;
    private javax.swing.JTextField txt_modelnumber;
    // End of variables declaration//GEN-END:variables
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
}
