/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclerentalservice;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author rr1
 */
public class AdminRemoveModel extends javax.swing.JFrame {

    /**
     * Creates new form AdminRemoveModel
     */
    public AdminRemoveModel() {
        initComponents();
        con=null;
        pst=null;
        rs=null;
        String[] col_names={"ID","Brand","Model Name","Seating Capacity","Release Date","Fuel Capacity"};
        try {
            con = new Connector().getCon();
            pst = con.prepareStatement("SELECT * FROM vehicle_rental.vehicle_model;");
            rs = pst.executeQuery();
            table_models.setModel(DbUtils.resultSetToTableModel(rs));
            
            for(int i=0;i<col_names.length;i++)
                table_models.getColumnModel().getColumn(i).setHeaderValue(col_names[i]);
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Linking Error. Contact admin.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
        } finally {
            if(con!=null) {
                try {
                    con.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
                }
            }
            if(pst!=null) {
                try {
                    pst.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_vehiclerentalservice = new javax.swing.JLabel();
        lbl_removemodel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_models = new javax.swing.JTable();
        btn_removemodel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(123, 104, 238));

        lbl_vehiclerentalservice.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_vehiclerentalservice.setForeground(new java.awt.Color(255, 255, 255));
        lbl_vehiclerentalservice.setText("VEHICLE RENTAL SERVICE");

        lbl_removemodel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_removemodel.setForeground(new java.awt.Color(255, 255, 255));
        lbl_removemodel.setText("REMOVE MODEL");

        table_models.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table_models);

        btn_removemodel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        btn_removemodel.setText("REMOVE MODEL");
        btn_removemodel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removemodelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_removemodel, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(279, 279, 279)
                            .addComponent(lbl_removemodel))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(145, 145, 145)
                            .addComponent(lbl_vehiclerentalservice))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(42, 42, 42)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_vehiclerentalservice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_removemodel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btn_removemodel)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_removemodelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removemodelActionPerformed
        // TODO add your handling code here:
        int r=table_models.getSelectedRow();
        String id;
        if(r==-1)
            JOptionPane.showMessageDialog(null,"Select a car.");
        else {
            id=table_models.getModel().getValueAt(r, 0).toString();
            
            try {
                con = new Connector().getCon();
                pst = con.prepareStatement("SELECT * FROM vehicle_rental.rental_car WHERE model=? ");
                pst.setString(1, id);
                rs=pst.executeQuery();
                if(rs.next()) {
                    JOptionPane.showMessageDialog(null,"First remove all cars of this model.");
                }
                else {
                    pst = con.prepareStatement("DELETE FROM `vehicle_rental`.`vehicle_model` WHERE (`id` = ?);");
                    pst.setString(1, id);
                    if(pst.executeUpdate()!=1)
                        JOptionPane.showMessageDialog(null,"Error. Contact admin.");
                    else
                        JOptionPane.showMessageDialog(null,"Model Removed");
                    pst = con.prepareStatement("SELECT * FROM vehicle_rental.vehicle_model;");
                    rs = pst.executeQuery();
                    table_models.setModel(DbUtils.resultSetToTableModel(rs));
                }
                    
            } catch (ClassNotFoundException ex) {
                JOptionPane.showMessageDialog(null,"Linking Error. Contact admin.");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
            } finally {
                if(con!=null) {
                    try {
                        con.close();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
                    }
                }
                if(pst!=null) {
                    try {
                        pst.close();
                    } catch (SQLException ex) {
                        JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
                    }
                }
            }
        }
    }//GEN-LAST:event_btn_removemodelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminRemoveModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminRemoveModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminRemoveModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminRemoveModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminRemoveModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_removemodel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_removemodel;
    private javax.swing.JLabel lbl_vehiclerentalservice;
    private javax.swing.JTable table_models;
    // End of variables declaration//GEN-END:variables
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
}
