/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclerentalservice;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author rr1
 */
public class AdminViewProfile extends javax.swing.JFrame {

    /**
     * Creates new form AdminViewProfile
     */
    public AdminViewProfile(String username) {
        initComponents();
        con=null;
        pst=null;
        rs=null;
        
        fetch(username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_vehiclerentalservice = new javax.swing.JLabel();
        lbl_viewprofile = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        lbl_name = new javax.swing.JLabel();
        lbl_licensenumber = new javax.swing.JLabel();
        lbl_usernameresult = new javax.swing.JLabel();
        lbl_nameresult = new javax.swing.JLabel();
        lbl_licencenumberresult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(123, 104, 238));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        lbl_vehiclerentalservice.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_vehiclerentalservice.setForeground(new java.awt.Color(255, 255, 255));
        lbl_vehiclerentalservice.setText("VEHICLE RENTAL SERVICE");

        lbl_viewprofile.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_viewprofile.setForeground(new java.awt.Color(255, 255, 255));
        lbl_viewprofile.setText("View Profile");

        lbl_username.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setText("Username");

        lbl_name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_name.setForeground(new java.awt.Color(255, 255, 255));
        lbl_name.setText("Name");

        lbl_licensenumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_licensenumber.setForeground(new java.awt.Color(255, 255, 255));
        lbl_licensenumber.setText("Licence Number");

        lbl_usernameresult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_usernameresult.setForeground(new java.awt.Color(255, 255, 255));
        lbl_usernameresult.setText("jLabel1");

        lbl_nameresult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_nameresult.setForeground(new java.awt.Color(255, 255, 255));
        lbl_nameresult.setText("jLabel1");

        lbl_licencenumberresult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_licencenumberresult.setForeground(new java.awt.Color(255, 255, 255));
        lbl_licencenumberresult.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(lbl_vehiclerentalservice))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(lbl_viewprofile))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_username)
                            .addComponent(lbl_name)
                            .addComponent(lbl_licensenumber))
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_licencenumberresult)
                            .addComponent(lbl_nameresult)
                            .addComponent(lbl_usernameresult))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lbl_vehiclerentalservice)
                .addGap(26, 26, 26)
                .addComponent(lbl_viewprofile)
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_username)
                    .addComponent(lbl_usernameresult))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(lbl_nameresult))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_licensenumber)
                    .addComponent(lbl_licencenumberresult))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fetch(String username) {
        try {
            con=new Connector().getCon();
            pst=con.prepareStatement("SELECT * FROM vehicle_rental.users WHERE username=?;");
            pst.setString(1,username);
            rs=pst.executeQuery();
            rs.next();
            lbl_nameresult.setText(rs.getString(2));
            lbl_usernameresult.setText(rs.getString(1));
            lbl_licencenumberresult.setText(rs.getString(4));
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Linking Error. Contact System Admin.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Database Error. Contact System Admin.");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminViewProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminViewProfile("User2").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_licencenumberresult;
    private javax.swing.JLabel lbl_licensenumber;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_nameresult;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel lbl_usernameresult;
    private javax.swing.JLabel lbl_vehiclerentalservice;
    private javax.swing.JLabel lbl_viewprofile;
    // End of variables declaration//GEN-END:variables
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
}
