/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclerentalservice;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author rr1
 */
public class AdminUpdateCarSub extends javax.swing.JFrame {

    /**
     * Creates new form AdminUpdateCarSub
     */
    public AdminUpdateCarSub(String id, Thread thread) {
        initComponents();
        con=null;
        pst=null;
        rs=null;
        this.id = id;
        this.thread=thread;
        try {
            con = new Connector().getCon();
            pst = con.prepareStatement("SELECT * FROM vehicle_rental.rental_car WHERE ID=?;");
            pst.setString(1,id);
            rs = pst.executeQuery();
            rs.next();
            txt_model.setText(rs.getString((2)));
            txt_enginenumber.setText(rs.getString(3));
            txt_buydate.setText(rs.getString(4));
            cb_carcondition.setSelectedItem(rs.getString(5));
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Linking Error. Contact admin.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
        } finally {
            if(con!=null) {
                try {
                    con.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
                }
            }
            if(pst!=null) {
                try {
                    pst.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
                }
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_newdetails = new javax.swing.JLabel();
        lbl_model = new javax.swing.JLabel();
        lbl_enginenumber = new javax.swing.JLabel();
        lbl_buydate = new javax.swing.JLabel();
        lbl_carcondition = new javax.swing.JLabel();
        txt_model = new javax.swing.JTextField();
        txt_enginenumber = new javax.swing.JTextField();
        txt_buydate = new javax.swing.JTextField();
        btn_update = new javax.swing.JButton();
        cb_carcondition = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(123, 104, 238));
        jPanel1.setForeground(new java.awt.Color(123, 104, 238));

        lbl_newdetails.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_newdetails.setForeground(new java.awt.Color(255, 255, 255));
        lbl_newdetails.setText("New Details");

        lbl_model.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_model.setForeground(new java.awt.Color(255, 255, 255));
        lbl_model.setText("Model");

        lbl_enginenumber.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_enginenumber.setForeground(new java.awt.Color(255, 255, 255));
        lbl_enginenumber.setText("Engine Number");

        lbl_buydate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_buydate.setForeground(new java.awt.Color(255, 255, 255));
        lbl_buydate.setText("Buy Date [yyyy-mm-dd]");

        lbl_carcondition.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_carcondition.setForeground(new java.awt.Color(255, 255, 255));
        lbl_carcondition.setText("Car Condition");

        btn_update.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_update.setText("UPDATE");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        cb_carcondition.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cb_carcondition.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Excellent", "Good", "Average", "Bad", "Poor" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(lbl_newdetails)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_update, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_model)
                            .addComponent(lbl_enginenumber)
                            .addComponent(lbl_buydate)
                            .addComponent(lbl_carcondition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_buydate, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                            .addComponent(txt_enginenumber)
                            .addComponent(txt_model)
                            .addComponent(cb_carcondition, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_newdetails)
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_model)
                    .addComponent(txt_model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_enginenumber)
                    .addComponent(txt_enginenumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_buydate)
                    .addComponent(txt_buydate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_carcondition)
                    .addComponent(cb_carcondition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btn_update)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        try {
            con = new Connector().getCon();
            pst = con.prepareStatement("SELECT * FROM vehicle_rental.vehicle_model WHERE ID=?;");
            pst.setString(1,txt_model.getText());
            rs = pst.executeQuery();
            if(rs.next()) {
                pst = con.prepareStatement("UPDATE `vehicle_rental`.`rental_car` SET `model` = ?, `engine_no` = ?, `buy_date` = ?, `car_condition` = ? WHERE (`id` = ?);");
                pst.setString(1, txt_model.getText());
                pst.setString(2, txt_enginenumber.getText());
                pst.setString(3, txt_buydate.getText());
                pst.setString(4, cb_carcondition.getSelectedItem().toString());
                pst.setString(5, id);
                if(pst.executeUpdate()==1) {
                    JOptionPane.showMessageDialog(null,"Successfully updated");
                }
                else {
                    JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
                }
            }
            else {
                JOptionPane.showMessageDialog(null,"Model doesnot exist.");
            }
   
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Linking Error. Contact admin.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
            ex.printStackTrace();
        } finally {
            if(con!=null) {
                try {
                    con.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
                }
            }
            if(pst!=null) {
                try {
                    pst.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
                }
            }
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUpdateCarSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUpdateCarSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUpdateCarSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUpdateCarSub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUpdateCarSub("1",null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_update;
    private javax.swing.JComboBox<String> cb_carcondition;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_buydate;
    private javax.swing.JLabel lbl_carcondition;
    private javax.swing.JLabel lbl_enginenumber;
    private javax.swing.JLabel lbl_model;
    private javax.swing.JLabel lbl_newdetails;
    private javax.swing.JTextField txt_buydate;
    private javax.swing.JTextField txt_enginenumber;
    private javax.swing.JTextField txt_model;
    // End of variables declaration//GEN-END:variables
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
    private String id;
    private Thread thread;
}
