/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclerentalservice;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author rr1
 */
public class AdminAddModel extends javax.swing.JFrame {

    /**
     * Creates new form AdminAddModel
     */
    public AdminAddModel() {
        initComponents();
        con=null;
        pst=null;
        rs=null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_vehiclerentalservice = new javax.swing.JLabel();
        lbl_addmodel = new javax.swing.JLabel();
        lbl_brand = new javax.swing.JLabel();
        lbl_modelname = new javax.swing.JLabel();
        lbl_seatingcapacity = new javax.swing.JLabel();
        lbl_releasedate = new javax.swing.JLabel();
        lbl_fuelcapacity = new javax.swing.JLabel();
        txt_brand = new javax.swing.JTextField();
        txt_modelname = new javax.swing.JTextField();
        txt_seatingcapacity = new javax.swing.JTextField();
        txt_releasedate = new javax.swing.JTextField();
        txt_fuelcapacity = new javax.swing.JTextField();
        btn_add = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(123, 104, 238));

        lbl_vehiclerentalservice.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lbl_vehiclerentalservice.setForeground(new java.awt.Color(255, 255, 255));
        lbl_vehiclerentalservice.setText("VEHICLE RENTAL SERVICE");

        lbl_addmodel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_addmodel.setForeground(new java.awt.Color(255, 255, 255));
        lbl_addmodel.setText("ADD MODEL");

        lbl_brand.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_brand.setForeground(new java.awt.Color(255, 255, 255));
        lbl_brand.setText("Brand");

        lbl_modelname.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_modelname.setForeground(new java.awt.Color(255, 255, 255));
        lbl_modelname.setText("Model Name");

        lbl_seatingcapacity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_seatingcapacity.setForeground(new java.awt.Color(255, 255, 255));
        lbl_seatingcapacity.setText("Seating Capacity");

        lbl_releasedate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_releasedate.setForeground(new java.awt.Color(255, 255, 255));
        lbl_releasedate.setText("Release Date [yyyy-mm-dd]");

        lbl_fuelcapacity.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_fuelcapacity.setForeground(new java.awt.Color(255, 255, 255));
        lbl_fuelcapacity.setText("Fuel Capacity");

        btn_add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btn_add.setText("ADD");
        btn_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(lbl_vehiclerentalservice))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(lbl_addmodel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_add, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_fuelcapacity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_fuelcapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_releasedate)
                                    .addComponent(lbl_brand, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_modelname, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_seatingcapacity, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_brand, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_modelname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_seatingcapacity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_releasedate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(71, 71, 71))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_vehiclerentalservice)
                        .addGap(18, 18, 18)
                        .addComponent(lbl_addmodel)
                        .addGap(60, 60, 60)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_brand)
                            .addComponent(txt_brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_modelname)
                            .addComponent(txt_modelname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lbl_seatingcapacity))
                    .addComponent(txt_seatingcapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_releasedate)
                    .addComponent(txt_releasedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fuelcapacity)
                    .addComponent(txt_fuelcapacity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(btn_add)
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            con = new Connector().getCon();
            pst = con.prepareStatement("SELECT * FROM `vehicle_rental`.`vehicle_model` WHERE brand=? and model_name=? and seating_capacity=? and release_date=? and fuel_capacity=?;");
            pst.setString(1,txt_brand.getText());
            pst.setString(2, txt_modelname.getText());
            pst.setString(3,txt_seatingcapacity.getText());
            pst.setString(4, txt_releasedate.getText());
            pst.setString(5, txt_fuelcapacity.getText());
            rs=pst.executeQuery();
            if(rs.next()) {
                JOptionPane.showMessageDialog(null,"Model Already Exist");
            }
            else {
                pst=con.prepareStatement("INSERT INTO `vehicle_rental`.`vehicle_model` (`brand`, `model_name`, `seating_capacity`, `release_date`, `fuel_capacity`) VALUES (?, ?, ?, ?, ?);");
                pst.setString(1,txt_brand.getText());
                pst.setString(2, txt_modelname.getText());
                pst.setString(3,txt_seatingcapacity.getText());
                pst.setString(4, txt_releasedate.getText());
                pst.setString(5, txt_fuelcapacity.getText());
                if(pst.executeUpdate()!=1) {
                    JOptionPane.showMessageDialog(null,"Couldn't add model.");
                }
                else {
                    JOptionPane.showMessageDialog(null,"Model Added");
                    txt_brand.setText("");
                    txt_modelname.setText("");
                    txt_seatingcapacity.setText("");
                    txt_releasedate.setText("");
                    txt_fuelcapacity.setText("");
                    
                }
            }
            
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Linking Error. Contact admin.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
        } finally {
            if(con!=null) {
                try {
                    con.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
                }
            }
            if(pst!=null) {
                try {
                    pst.close();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null,"Database Error. Contact admin.");
                }
            }
        }
        
    }//GEN-LAST:event_btn_addActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_addmodel;
    private javax.swing.JLabel lbl_brand;
    private javax.swing.JLabel lbl_fuelcapacity;
    private javax.swing.JLabel lbl_modelname;
    private javax.swing.JLabel lbl_releasedate;
    private javax.swing.JLabel lbl_seatingcapacity;
    private javax.swing.JLabel lbl_vehiclerentalservice;
    private javax.swing.JTextField txt_brand;
    private javax.swing.JTextField txt_fuelcapacity;
    private javax.swing.JTextField txt_modelname;
    private javax.swing.JTextField txt_releasedate;
    private javax.swing.JTextField txt_seatingcapacity;
    // End of variables declaration//GEN-END:variables
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
}
