/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vehiclerentalservice;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author rr1
 */
public class Registration extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     */
    public Registration() {
        initComponents();
        con=null;
        pst=null;
        rs=null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_registration = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        lbl_name = new javax.swing.JLabel();
        txt_name = new javax.swing.JTextField();
        lbl_password = new javax.swing.JLabel();
        psw_password = new javax.swing.JPasswordField();
        lbl_confirmpassword = new javax.swing.JLabel();
        psw_confirmpassword = new javax.swing.JPasswordField();
        lbl_licence = new javax.swing.JLabel();
        txt_licence = new javax.swing.JTextField();
        btn_register = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbl_registration.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        lbl_registration.setText("REGISTRATION");

        lbl_username.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_username.setText("Username");

        lbl_name.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_name.setText("Name");

        lbl_password.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_password.setText("Password");

        lbl_confirmpassword.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_confirmpassword.setText("Confirm Password");

        lbl_licence.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        lbl_licence.setText("Licence Number");

        btn_register.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        btn_register.setText("REGISTER");
        btn_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(lbl_registration))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_username)
                            .addComponent(lbl_name)
                            .addComponent(lbl_password)
                            .addComponent(lbl_confirmpassword)
                            .addComponent(lbl_licence))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_username)
                            .addComponent(txt_name)
                            .addComponent(psw_password)
                            .addComponent(psw_confirmpassword)
                            .addComponent(txt_licence, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_registration)
                        .addGap(54, 54, 54)
                        .addComponent(lbl_username))
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_name)
                    .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(psw_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_password))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_confirmpassword)
                    .addComponent(psw_confirmpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_licence)
                    .addComponent(txt_licence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addComponent(btn_register, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registerActionPerformed
        // TODO add your handling code here:
        String username;
        String password;
        String repassword;
        try {
            

            con = new Connector().getCon();
            username = txt_username.getText();
            if(username.equals("")) {
                JOptionPane.showMessageDialog(null,"Username cannot be empty");
                
            }
            else {
                password = new String(psw_password.getPassword());
                repassword = new String(psw_confirmpassword.getPassword());
              if(password.equals("")) {
                  JOptionPane.showMessageDialog(null,"Password cannot be empty");
              }
              else {
                  if(password.equals(repassword)) {
                    
                        pst = con.prepareStatement("SELECT * FROM `vehicle_rental`.`users` WHERE username = ?");
                        pst.setString(1,username);
                        //pst.setString(2,HashingPassword.generateHash(password));
                        //pst.setInt(3,cb_loginas.getSelectedIndex());
                        rs = pst.executeQuery();
                        if(rs.next()) 
                            JOptionPane.showMessageDialog(null,"Username Already Exist");
                        else{
                            pst = con.prepareStatement("INSERT INTO `vehicle_rental`.`users` (`username`, `name`, `password`, `licence_no`, `is_admin`) VALUES (?, ?, ?, ?, '0');");
                            pst.setString(1,username);
                            pst.setString(2,txt_name.getText());
                            pst.setString(3,HashingPassword.generateHash(password));
                            pst.setString(4,txt_licence.getText());
                            if(pst.executeUpdate() !=1 )
                                JOptionPane.showMessageDialog(null,"Database state error");
                            else
                                JOptionPane.showMessageDialog(null,"Successfully Registered");
                        }
                   }
                  else {
                        JOptionPane.showMessageDialog(null,"Password don't match");
                  }
                  
              }
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null,"Connection Error");
            ex.printStackTrace();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Database State Error");
            ex.printStackTrace();
        }
        finally {
            try {
                if(pst!=null)
                    pst.close();
                if(con!=null)
                    con.close();
            } catch(Exception e) {
                JOptionPane.showMessageDialog(null,"Connection Error");
                e.printStackTrace();
            }
            
        }
    }//GEN-LAST:event_btn_registerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_register;
    private javax.swing.JLabel lbl_confirmpassword;
    private javax.swing.JLabel lbl_licence;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_password;
    private javax.swing.JLabel lbl_registration;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JPasswordField psw_confirmpassword;
    private javax.swing.JPasswordField psw_password;
    private javax.swing.JTextField txt_licence;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;

}
